[fix] change regular expression of key
apache/servicecomb-kie pull request #249
Opened 2022-07-28 12:59 UTC by kkf1

2022-07-28 14:41 UTC, little-cui requested changes

2022-07-28 14:41 UTC, little-cui commented on pkg/validator/rule.go
> +	validator.NewRegexRule(key, keyRegex),
请补充UT，对修改进行保护

2022-07-29 09:21 UTC, tianxiaoliang commented
似乎无法向前兼容

2022-07-29 09:22 UTC, tianxiaoliang commented
release的时候必须写个breaking change

2022-07-29 09:26 UTC, little-cui approved these changes

2022-07-29 09:31 UTC, merged